name: vi_test

on:
  push:
    paths-ignore:
      - '**.md'
    
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup ROS
        run: |
         git clone https://github.com/ryuichiueda/ros_setup_scripts_Ubuntu18.04_desktop
         cd ros_setup_scripts_Ubuntu18.04_desktop
         bash step0.bash
         bash step1.bash
         curl -sSL http://get.gazebosim.org | sh
         sudo apt-get install ros-melodic-tf ros-melodic-map-server xvfb
         sudo pip3 install rospkg
         mkdir -p ~/.ros/log/
      - name: Build catkin_ws
        run: |
         source /opt/ros/melodic/setup.bash
         mkdir -p ~/catkin_ws/src
         cd ~/catkin_ws/src
         git clone -b "${GITHUB_REF#refs/heads/}" https://github.com/ryuichiueda/emcl.git
         git clone -b "${GITHUB_REF#refs/heads/}" https://github.com/ROBOTIS-GIT/turtlebot3.git
         git clone -b "${GITHUB_REF#refs/heads/}" https://github.com/ROBOTIS-GIT/turtlebot3_gazebo_plugin.git
         git clone -b "${GITHUB_REF#refs/heads/}" https://github.com/ROBOTIS-GIT/turtlebot3_msgs.git
         git clone -b "${GITHUB_REF#refs/heads/}" https://github.com/ROBOTIS-GIT/turtlebot3_simulations.git
         cd ../
         catkin_make
      - name: Execute and Test
        run: |
         source /opt/ros/melodic/setup.bash
         source ~/catkin_ws/devel/setup.bash
         ~/catkin_ws/src/emcl/test/er_test.bash
